#Plik makefile dla myhuffman


all: myhuffman.cpp decode.cpp
	g++ myhuffman.cpp -o myhuffman
	g++ decode.cpp -o decode
	
myhuffman: myhuffman.cpp
	g++ myhuffman.cpp -o myhuffman
	
decode: decode.cpp
	g++ decode.cpp -o decode

clean:
	rm -f myhuffman decode
	
