#Plik makefile dla zad1, zad2, zad3, zad4, zad5, zad6



all: zad1.c zad2.c zad3.c zad4.c zad5.c zad6.c
	$gcc zad1.c -o zad1
	$gcc zad2.c -o zad2
	$gcc zad3.c -o zad3
	$gcc zad4.c -o zad4
	$gcc zad5.c -o zad5
	$gcc zad6.c -o zad6

zad1: zad1.c
	$gcc zad1.c -o zad1

zad2: zad2.c
	$gcc zad2.c -o  zad2

zad3: zad3.c
	$gcc zad3.c -o  zad3

zad4: zad4.c
	$gcc zad4.c -o  zad4

zad5: zad5.c
	$gcc zad5.c -o  zad5

zad6: zad6.c
	$gcc zad6.c -o  zad6

clean:
	rm -f zad1 zad2 zad3  zad4 zad5 zad6
